---
- name: Install Oracle
  hosts: oracle
  become: true
  roles:
    - { role: oracle }
# @TODO deprecated
# - name: Install Monitor
#   hosts: monitor
#   become: true
#   roles:
#     - { role: monitor }
