---
## General settings
ORACLE_BRIDGE_MODE: "ERC_TO_NATIVE"
ORACLE_ALLOW_HTTP_FOR_RPC: yes
ORACLE_LOG_LEVEL: info

## Home contract
COMMON_HOME_RPC_URL: "https://rpc.ankr.com/gnosis"
ORACLE_HOME_RPC_POLLING_INTERVAL: 15000
COMMON_HOME_BRIDGE_ADDRESS: "0x7301CFA0e1756B71869E93d4e4Dca5c7d0eb0AA6"

## Foreign contract
COMMON_FOREIGN_RPC_URL: "https://mainnet.infura.io/v3/<infura_key>"
ORACLE_FOREIGN_RPC_POLLING_INTERVAL: 24000
COMMON_FOREIGN_BRIDGE_ADDRESS: "0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016"

ORACLE_TX_REDUNDANCY: true
ORACLE_HOME_TX_RESEND_INTERVAL: 300000

## Home Gasprice
COMMON_HOME_GAS_PRICE_SUPPLIER_URL: "eip1559-gas-estimation"
COMMON_HOME_GAS_PRICE_SPEED_TYPE: "fast"
COMMON_HOME_GAS_PRICE_FALLBACK: 2000000000      # in wei
COMMON_HOME_GAS_PRICE_FACTOR: 1
ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL: 600000

## Foreign Gasprice
COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL: "eip1559-gas-estimation"
COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE: "fast"
COMMON_FOREIGN_GAS_PRICE_FALLBACK: 100000000000   # in wei
COMMON_FOREIGN_GAS_PRICE_FACTOR: 1
ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL: 600000

QUEUE_URL: "amqp://rabbit"
REDIS_URL: "redis://redis"

## BEGIN Calculated by scripts/getValidatorStartBlocks.js
# ORACLE_HOME_START_BLOCK: 25106875
# ORACLE_FOREIGN_START_BLOCK: 16027237
## END Calculated by scripts/getValidatorStartBlocks.js
